version: '3'

services:
  flask:
    build: ./flask
    container_name: flask
    ports:
      - "8080:5000"
    networks:
      - scrapy_mysql_net
    command: ["python", "app.py"]
    restart: on-failure

  scraper:
    build: ./scraper
    container_name: scraper
    networks:
      - scrapy_mysql_net
    command: ["wait-for-it", "db:3306", "--timeout=120", "--", "scrapy", "crawl", "fvs"]
    restart: on-failure

  db:
    image: mysql
    container_name: db
    command: ["--init-file=/tmp/mysql-init.sql", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/db_dir:/var/lib/mysql
      - ./db/mysql-init.sql:/tmp/mysql-init.sql
    networks:
      - scrapy_mysql_net
    ports:
      - "3307:3306"
    expose:
      - 3306

volumes:
  db_dir:

networks:
  scrapy_mysql_net:
